<h2>Браузеры пользователей</h2>

<div class="PaneButtons">
  {{ @buttons }}
</div>
<div>
  &nbsp;&nbsp;&nbsp;
  <img src="browsers_statistic.png" alt=""/>
</div>
<br/>
<div class="table">

    <div class="table-head">
      <span class="Mname" >Версия браузера</span>
      <span class="Mlink" >Количество просмотров</span>
      <span class="Mactions">Соотношение</span>
    </div>

  {% for @browser in @browsers %}
    <div class="table-row">

        <span class="Mname"><span class="custom-label blueUi">{{ @browser.ua }}</span></span>
        <span class="Mlink"><span class="custom-number redUi">{{ @browser.count }}</span></span>
        <span class="Mactions">{{ @browser.percents }}%</span>

    </div>
  {% endif %}
</div>