<h2>Источники переходов</h2>

<div class="PaneButtons">
  {{ @buttons }}
</div>
<div>
  &nbsp;&nbsp;&nbsp;
  <img src="pages_referer.png" alt=""/>
</div>

<div class="table">

    <div class="table-head">
      <span class="Mname" >Адрес страницы</span>
      <span class="Mlink" >Количество просмотров</span>
      <span class="Mactions">Соотношение</span>
    </div>

  {% for @ref in @refs %}
    <div class="table-row">

        <span class="Mname"><a target="_blank" href="http://{{ @_SERVER.HTTP_HOST ~~~ @ref.referer }}">{{ @ref.referer }}</a></span>
        <span class="Mlink"><span class="custom-number redUi">{{ @ref.count }}</span></span>
        <span class="Mactions">{{ @ref.percents }}%</span>

    </div>
  {% endif %}
</div>