<h2>Редактор меню</h2>

<div class="PaneButtons">
  {{ @buttons }}
</div>

{% if isset(@_GET.success) %}
<div class="system_success" style="display:block">
  <span class="bold">Системное сообщение:</span><span class="close">×</span>
  <p>Изменения успешно сохранены</p>
</div><br/><br/>
{% endif %}

{% for @parent in @first_level %}
<span class="custom-label greyUi" style="color:white;font-size: 14px;">&laquo;{{ @parent.name }}&raquo;</span>
  <div class="table">

    <div class="table-head">
      <span class="Mname" >Название</span>
      <span class="Mlink" >Путь</span>
      <span class="Mactions">Управление</span>
    </div>
      <div class="table-row">

        <span class="Mname"><span class="custom-label redUi">{{ @parent.name }}</span></span>
        <span class="Mlink"><span class="custom-label redUi">{{ @parent.url }}</span></span>
        <span class="Mactions">
          <button class="data-load button buttonBlueUi" href="/auth/menu/edit/{{ @parent.id }}">редактировать</button>
        </span>

      </div>
  {% for @child in @second_level %}

    {% if @child.parentId == @parent.id %}
      <div class="table-row">

        <span class="Mname"><span class="custom-label blueUi">{{ mb_substr(@child.name,0,60) }}...</span></span>
        <span class="Mlink"><span class="custom-label blueUi">{{ @child.url }}</span></span>
        <span class="Mactions">
          <button class="data-load button buttonBlueUi" href="/auth/menu/edit/{{ @child.id }}">редактировать</button>
        </span>

      </div>
    {% endif %}
  {% endfor %}
  </div>
  <br/><br/><br/><br/>
{% endfor %}