<h2>Добавление категории</h2>

<div class="paneButtons">
  {{ @buttons }}
</div>

<div class="system_warning" style="display: block">
  <span class="bold">Внимание!</span><span class="close">×</span>
  <p>Для того чтобы добавленная категория отображалась в списке к ней необходимо привязать хотя бы один элемент контента</p>
</div>
<br/>

<div class="system_success">
  <span class="bold">Системное сообщение:</span><span class="close">×</span>
</div>
<div class="system_error">
  <span class="bold">Ошибка!</span><span class="close">×</span>
</div><br/>

<div class="action_form">
{{ @webform }}
</div>