<h2>Браузеры пользователей</h2>

<div class="PaneButtons">
  <?php echo $buttons ?>
</div>
<div>
  &nbsp;&nbsp;&nbsp;
  <img src="browsers_statistic.png" alt=""/>
</div>
<br/>
<div class="table">

    <div class="table-head">
      <span class="Mname" >Версия браузера</span>
      <span class="Mlink" >Количество просмотров</span>
      <span class="Mactions">Соотношение</span>
    </div>

  <?php foreach($browsers as $browser){?>
    <div class="table-row">

        <span class="Mname"><span class="custom-label blueUi"><?php echo $browser["ua"] ?></span></span>
        <span class="Mlink"><span class="custom-number redUi"><?php echo $browser["count"] ?></span></span>
        <span class="Mactions"><?php echo $browser["percents"] ?>%</span>

    </div>
  <?php } ?>
</div>