<h2>Популярные страницы</h2>

<div class="PaneButtons">
  <?php echo $buttons ?>
</div>
<div>
  &nbsp;&nbsp;&nbsp;
  <img src="pages_statistic.png" alt=""/>
</div>

<div class="table">

    <div class="table-head">
      <span class="Mname" >Адрес страницы</span>
      <span class="Mlink" >Количество просмотров</span>
      <span class="Mactions">Соотношение</span>
    </div>

  <?php foreach($pages as $page){?>
    <div class="table-row">

        <span class="Mname"><a target="_blank" href="http://<?php echo $_SERVER["HTTP_HOST"] . $page["url"] ?>"><?php echo $page["url"] ?></a></span>
        <span class="Mlink"><span class="custom-number redUi"><?php echo $page["count"] ?></span></span>
        <span class="Mactions"><?php echo $page["percents"] ?>%</span>

    </div>
  <?php } ?>
</div>