<h2>Редактирование</h2>

<div class="PaneButtons">
  <?php echo $buttons ?>
</div>

<div class="system_success">
  <span class="bold">Системное сообщение:</span><span class="close">×</span>
</div>
<div class="system_error">
  <span class="bold">Ошибка!</span><span class="close">×</span>
</div><br/>

<div class="action_form">
<?php echo $webformEdit ?>
</div>
<div class="delete_form" style="left: 120px;">
<?php echo $webformDelete ?>
</div>