<div class="pagination">
<?php if($pagesCount > 1 ) {?>
  <?php if($currentPage != 1 ) {?>
    <button class="small-button buttonGreyUi data-load" href="<?php echo $link . ($currentPage - 1) ?>">&laquo; Предыдущая</button>
    <?php } ?>
    <?php for($i=0;$i<$pagesCount;$i++){ ?>
      <?php if($i+1==$currentPage ) {?>
        <?php $class="Black" ?>
      <?php } else {?>
        <?php $class="Grey" ?>
      <?php } ?>
      <button class="small-button button<?php echo $class ?>Ui data-load" href="<?php echo $link . ($i+1) ?>">
        <?php echo $i+1 ?>
      </button>
    <?php } ?>
    <?php if($currentPage != $pagesCount ) {?>
    <button class="small-button buttonGreyUi data-load" href="<?php echo $link . ($currentPage + 1) ?>">Следующая &raquo;</button>
  <?php } ?>
<?php } ?>
</div>