<div class="pagination">
{% if @pagesCount > 1 %}
  {% if @currentPage != 1 %}
    <button class="small-button buttonGreyUi data-load" href="{{ @link ~~~ (@currentPage - 1) }}">&laquo; Предыдущая</button>
    {% endif %}
    {% for @i in range(0,@pagesCount) %}
      {% if @i+1==@currentPage %}
        {% @class="Black" %}
      {% else %}
        {% @class="Grey" %}
      {% endif %}
      <button class="small-button button{{ @class }}Ui data-load" href="{{ @link ~~~ (@i+1) }}">
        {{ @i+1 }}
      </button>
    {% endfor %}
    {% if @currentPage != @pagesCount %}
    <button class="small-button buttonGreyUi data-load" href="{{ @link ~~~ (@currentPage + 1) }}">Следующая &raquo;</button>
  {% endif %}
{% endif %}
</div>